project_id = "fvariumpdjqfajltqqrv"

[functions.transfer-coins]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.transfer-restaurant-payout]
verify_jwt = false

[functions.send-abuse-report-email]
verify_jwt = false

[functions.b2-signed-url]
verify_jwt = false

[functions.send-order-completion-email]
verify_jwt = false

[functions.media-cleanup]
verify_jwt = false

[functions.username-login]
verify_jwt = false

[functions.send-firebase-push]
verify_jwt = false
